/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zapateria;

import local.Caballero;
import static zapateria.vtnPrincipal.obj;
import static zapateria.vtnPrincipal.obj2;
import cjb.ci.Mensaje;
import cjb.ci.Validaciones;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JTextField;
import poo.LecturasA;

/**
 *
 * @author PC
 */
public class vtnACaballero extends javax.swing.JFrame
{

    /**
     * Creates new form vtnASucu
     */
    public vtnACaballero()
    {
        initComponents();
        setIconImage(getIconImage());
    }

    //Icono del jframe
    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        posSucu = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JPanel();
        siguiente = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        cancelar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        costo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        SoN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCambiar = new javax.swing.JPanel();
        cambiar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        anio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tipocalzado = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnTerminar = new javax.swing.JPanel();
        terminar = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        btnCancelar1 = new javax.swing.JPanel();
        cancelar1 = new javax.swing.JLabel();
        btnCambiar1 = new javax.swing.JPanel();
        cambiar1 = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JPanel();
        siguiente1 = new javax.swing.JLabel();
        btnTerminar1 = new javax.swing.JPanel();
        terminar1 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Por favor, llene todos los campos.");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 250, 30));

        posSucu.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        posSucu.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                posSucuCaretUpdate(evt);
            }
        });
        posSucu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posSucuActionPerformed(evt);
            }
        });
        posSucu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                posSucuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                posSucuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                posSucuKeyTyped(evt);
            }
        });
        jPanel1.add(posSucu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 70, -1));

        btnSiguiente.setBackground(new java.awt.Color(145, 58, 68));
        btnSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguiente.setEnabled(false);
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseEntered(evt);
            }
        });
        btnSiguiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSiguienteKeyPressed(evt);
            }
        });

        siguiente.setBackground(new java.awt.Color(255, 255, 255));
        siguiente.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        siguiente.setForeground(new java.awt.Color(255, 255, 255));
        siguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente.setText("SIGUIENTE");
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        siguiente.setEnabled(false);
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siguienteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSiguienteLayout = new javax.swing.GroupLayout(btnSiguiente);
        btnSiguiente.setLayout(btnSiguienteLayout);
        btnSiguienteLayout.setHorizontalGroup(
            btnSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        btnSiguienteLayout.setVerticalGroup(
            btnSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSiguienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 140, 40));

        btnCancelar.setBackground(new java.awt.Color(145, 58, 68));
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
        });
        btnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelarKeyPressed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar.setText("CANCELAR");
        cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnCancelarLayout = new javax.swing.GroupLayout(btnCancelar);
        btnCancelar.setLayout(btnCancelarLayout);
        btnCancelarLayout.setHorizontalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCancelarLayout.setVerticalGroup(
            btnCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelarLayout.createSequentialGroup()
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 140, 40));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Tipo de Modelo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, 30));

        fecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        fecha.setEnabled(false);
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fechaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaKeyTyped(evt);
            }
        });
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 150, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Costo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 210, 30));

        costo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        costo.setEnabled(false);
        costo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoActionPerformed(evt);
            }
        });
        costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                costoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoKeyTyped(evt);
            }
        });
        jPanel1.add(costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 150, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setText("¿Está pagado? Digite S o N");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 210, 30));

        SoN.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        SoN.setText("S (sí) / N (no)");
        SoN.setEnabled(false);
        SoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoNActionPerformed(evt);
            }
        });
        SoN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SoNKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SoNKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SoNKeyTyped(evt);
            }
        });
        jPanel1.add(SoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 150, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEPARTAMENTO: CABALLERO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 380, 80));

        btnCambiar.setBackground(new java.awt.Color(145, 58, 68));
        btnCambiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCambiarMouseEntered(evt);
            }
        });

        cambiar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        cambiar.setForeground(new java.awt.Color(255, 255, 255));
        cambiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambiar.setText("CAMBIAR");
        cambiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cambiarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnCambiarLayout = new javax.swing.GroupLayout(btnCambiar);
        btnCambiar.setLayout(btnCambiarLayout);
        btnCambiarLayout.setHorizontalGroup(
            btnCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        btnCambiarLayout.setVerticalGroup(
            btnCambiarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 110, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel7.setText("Digite la posición de la sucursal:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 190, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setText("Modelo:");
        jLabel8.setEnabled(false);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 70, 30));

        modelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        modelo.setText("1234567890");
        modelo.setEnabled(false);
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });
        modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modeloKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modeloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modeloKeyTyped(evt);
            }
        });
        jPanel1.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 150, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel9.setText("Talla:");
        jLabel9.setEnabled(false);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 40, 30));

        anio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        anio.setEnabled(false);
        anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioActionPerformed(evt);
            }
        });
        anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                anioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                anioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioKeyTyped(evt);
            }
        });
        jPanel1.add(anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 150, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setText("Tipo de calzado: ");
        jLabel10.setEnabled(false);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 100, 30));

        tipocalzado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tipocalzado.setEnabled(false);
        tipocalzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipocalzadoActionPerformed(evt);
            }
        });
        tipocalzado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipocalzadoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tipocalzadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tipocalzadoKeyTyped(evt);
            }
        });
        jPanel1.add(tipocalzado, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 150, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setText("Llene los datos del Calzado");
        jLabel12.setEnabled(false);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 200, 30));

        btnTerminar.setBackground(new java.awt.Color(145, 58, 68));
        btnTerminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTerminarMouseEntered(evt);
            }
        });
        btnTerminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTerminarKeyPressed(evt);
            }
        });

        terminar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        terminar.setForeground(new java.awt.Color(255, 255, 255));
        terminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        terminar.setText("TERMINAR");
        terminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        terminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                terminarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnTerminarLayout = new javax.swing.GroupLayout(btnTerminar);
        btnTerminar.setLayout(btnTerminarLayout);
        btnTerminarLayout.setHorizontalGroup(
            btnTerminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTerminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnTerminarLayout.setVerticalGroup(
            btnTerminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTerminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 70, 30));

        btnCancelar1.setBackground(new java.awt.Color(97, 5, 16));
        btnCancelar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnCancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelar1MouseExited(evt);
            }
        });
        btnCancelar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelar1KeyPressed(evt);
            }
        });

        cancelar1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        cancelar1.setForeground(new java.awt.Color(255, 255, 255));
        cancelar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelar1.setText("CANCELAR");
        cancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cancelar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCancelar1Layout = new javax.swing.GroupLayout(btnCancelar1);
        btnCancelar1.setLayout(btnCancelar1Layout);
        btnCancelar1Layout.setHorizontalGroup(
            btnCancelar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelar1Layout.createSequentialGroup()
                .addComponent(cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        btnCancelar1Layout.setVerticalGroup(
            btnCancelar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelar1Layout.createSequentialGroup()
                .addComponent(cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 140, 40));

        btnCambiar1.setBackground(new java.awt.Color(97, 5, 16));
        btnCambiar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnCambiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCambiar1MouseExited(evt);
            }
        });

        cambiar1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        cambiar1.setForeground(new java.awt.Color(255, 255, 255));
        cambiar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambiar1.setText("CAMBIAR");
        cambiar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cambiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cambiar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cambiar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCambiar1Layout = new javax.swing.GroupLayout(btnCambiar1);
        btnCambiar1.setLayout(btnCambiar1Layout);
        btnCambiar1Layout.setHorizontalGroup(
            btnCambiar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );
        btnCambiar1Layout.setVerticalGroup(
            btnCambiar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cambiar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jPanel1.add(btnCambiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 110, 30));

        btnSiguiente1.setBackground(new java.awt.Color(97, 5, 16));
        btnSiguiente1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnSiguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguiente1.setEnabled(false);
        btnSiguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseExited(evt);
            }
        });
        btnSiguiente1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSiguiente1KeyPressed(evt);
            }
        });

        siguiente1.setBackground(new java.awt.Color(255, 255, 255));
        siguiente1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        siguiente1.setForeground(new java.awt.Color(255, 255, 255));
        siguiente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente1.setText("SIGUIENTE");
        siguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        siguiente1.setEnabled(false);
        siguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguiente1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                siguiente1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSiguiente1Layout = new javax.swing.GroupLayout(btnSiguiente1);
        btnSiguiente1.setLayout(btnSiguiente1Layout);
        btnSiguiente1Layout.setHorizontalGroup(
            btnSiguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(siguiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        btnSiguiente1Layout.setVerticalGroup(
            btnSiguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSiguiente1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(siguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 140, 40));

        btnTerminar1.setBackground(new java.awt.Color(97, 5, 16));
        btnTerminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnTerminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTerminar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTerminar1MouseExited(evt);
            }
        });
        btnTerminar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTerminar1KeyPressed(evt);
            }
        });

        terminar1.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        terminar1.setForeground(new java.awt.Color(255, 255, 255));
        terminar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        terminar1.setText("TERMINAR");
        terminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        terminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                terminar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                terminar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTerminar1Layout = new javax.swing.GroupLayout(btnTerminar1);
        btnTerminar1.setLayout(btnTerminar1Layout);
        btnTerminar1Layout.setHorizontalGroup(
            btnTerminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTerminar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(terminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnTerminar1Layout.setVerticalGroup(
            btnTerminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnTerminar1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(terminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(btnTerminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        Fondo1.setBackground(new java.awt.Color(255, 0, 51));
        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes1/5.5.png"))); // NOI18N
        Fondo1.setEnabled(false);
        jPanel1.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void posSucuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_posSucuActionPerformed
    {//GEN-HEADEREND:event_posSucuActionPerformed

    }//GEN-LAST:event_posSucuActionPerformed

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cancelarMouseClicked
    {//GEN-HEADEREND:event_cancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    private void btnSiguienteKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnSiguienteKeyPressed
    {//GEN-HEADEREND:event_btnSiguienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteKeyPressed

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_siguienteMouseClicked
    {//GEN-HEADEREND:event_siguienteMouseClicked
        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()))
        {
            modelo.setEnabled(true);
            anio.setEnabled(true);
            tipocalzado.setEnabled(true);
            jLabel12.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jLabel10.setEnabled(true);
            btnTerminar.setVisible(true);
            terminar.setVisible(true);
            //QUITAR BOTON CAMBIAR
            this.btnCambiar.setVisible(false);
            this.cambiar.setVisible(false);
        } else
        {
            Mensaje.error(this, "Por favor, llene todos los campos.");
        }
    }//GEN-LAST:event_siguienteMouseClicked

    private void btnCancelarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnCancelarKeyPressed
    {//GEN-HEADEREND:event_btnCancelarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarKeyPressed

    private void posSucuKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_posSucuKeyTyped
    {//GEN-HEADEREND:event_posSucuKeyTyped
        Validaciones.validaEntero(evt, 3, posSucu.getText());
    }//GEN-LAST:event_posSucuKeyTyped

    private void posSucuKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_posSucuKeyPressed
    {//GEN-HEADEREND:event_posSucuKeyPressed
        Validaciones.enter(this, evt, new JTextField());
        if (evt.getKeyChar() == '\n')
        {
            if ("".equals(posSucu.getText()))
            {
                Mensaje.error(this, "Debe teclear la posición de la sucursal. Para salir, presione cancelar.");
            } else
            {
                fecha.setEnabled(true);
                costo.setEnabled(true);
                SoN.setEnabled(true);
                posSucu.setEnabled(false);
                this.btnCambiar.setVisible(true);
                this.cambiar.setVisible(true);
                if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()))
                {
                    btnSiguiente.setEnabled(true);
                    siguiente.setEnabled(true);
                }
            }
        }

    }//GEN-LAST:event_posSucuKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void costoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_costoActionPerformed
    {//GEN-HEADEREND:event_costoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoActionPerformed

    private void costoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_costoKeyPressed
    {//GEN-HEADEREND:event_costoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoKeyPressed

    private void costoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_costoKeyTyped
    {//GEN-HEADEREND:event_costoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_costoKeyTyped

    private void SoNActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SoNActionPerformed
    {//GEN-HEADEREND:event_SoNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoNActionPerformed

    private void SoNKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SoNKeyPressed
    {//GEN-HEADEREND:event_SoNKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoNKeyPressed

    private void SoNKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SoNKeyTyped
    {//GEN-HEADEREND:event_SoNKeyTyped

    }//GEN-LAST:event_SoNKeyTyped

    private void fechaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechaKeyTyped
    {//GEN-HEADEREND:event_fechaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaKeyTyped

    private void fechaKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechaKeyPressed
    {//GEN-HEADEREND:event_fechaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaKeyPressed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fechaActionPerformed
    {//GEN-HEADEREND:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void posSucuKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_posSucuKeyReleased
    {//GEN-HEADEREND:event_posSucuKeyReleased

    }//GEN-LAST:event_posSucuKeyReleased

    private void posSucuCaretUpdate(javax.swing.event.CaretEvent evt)//GEN-FIRST:event_posSucuCaretUpdate
    {//GEN-HEADEREND:event_posSucuCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_posSucuCaretUpdate

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        this.btnCambiar.setVisible(false);
        this.cambiar.setVisible(false);
        this.btnTerminar.setVisible(false);
        this.terminar.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void cambiarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cambiarMouseClicked
    {//GEN-HEADEREND:event_cambiarMouseClicked
        fecha.setEnabled(false);
        costo.setEnabled(false);
        SoN.setEnabled(false);
        posSucu.setEnabled(true);
        this.btnCambiar.setVisible(false);
        this.cambiar.setVisible(false);

    }//GEN-LAST:event_cambiarMouseClicked

    private void SoNKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_SoNKeyReleased
    {//GEN-HEADEREND:event_SoNKeyReleased
        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()))
        {
            btnSiguiente.setEnabled(true);
            siguiente.setEnabled(true);
        }
    }//GEN-LAST:event_SoNKeyReleased

    private void fechaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_fechaKeyReleased
    {//GEN-HEADEREND:event_fechaKeyReleased
        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()))
        {
            btnSiguiente.setEnabled(true);
            siguiente.setEnabled(true);
        }
    }//GEN-LAST:event_fechaKeyReleased

    private void costoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_costoKeyReleased
    {//GEN-HEADEREND:event_costoKeyReleased
        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()))
        {
            btnSiguiente.setEnabled(true);
            siguiente.setEnabled(true);
        }
    }//GEN-LAST:event_costoKeyReleased

    private void modeloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_modeloActionPerformed
    {//GEN-HEADEREND:event_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloActionPerformed

    private void modeloKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_modeloKeyPressed
    {//GEN-HEADEREND:event_modeloKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloKeyPressed

    private void modeloKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_modeloKeyReleased
    {//GEN-HEADEREND:event_modeloKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloKeyReleased

    private void modeloKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_modeloKeyTyped
    {//GEN-HEADEREND:event_modeloKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloKeyTyped

    private void anioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_anioActionPerformed
    {//GEN-HEADEREND:event_anioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioActionPerformed

    private void anioKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_anioKeyPressed
    {//GEN-HEADEREND:event_anioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioKeyPressed

    private void anioKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_anioKeyReleased
    {//GEN-HEADEREND:event_anioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_anioKeyReleased

    private void anioKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_anioKeyTyped
    {//GEN-HEADEREND:event_anioKeyTyped
        Validaciones.validaEntero(evt, 5, anio.getText());
    }//GEN-LAST:event_anioKeyTyped

    private void tipocalzadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tipocalzadoActionPerformed
    {//GEN-HEADEREND:event_tipocalzadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocalzadoActionPerformed

    private void tipocalzadoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tipocalzadoKeyPressed
    {//GEN-HEADEREND:event_tipocalzadoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocalzadoKeyPressed

    private void tipocalzadoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tipocalzadoKeyReleased
    {//GEN-HEADEREND:event_tipocalzadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocalzadoKeyReleased

    private void tipocalzadoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tipocalzadoKeyTyped
    {//GEN-HEADEREND:event_tipocalzadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tipocalzadoKeyTyped

    private void terminarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_terminarMouseClicked
    {//GEN-HEADEREND:event_terminarMouseClicked

        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()) && !"".equals(modelo.getText()) && !"".equals(anio.getText()) && !"".equals(tipocalzado.getText()))
        {
            if (Integer.parseInt(posSucu.getText()) < obj.getAutoServicios().size() && Integer.parseInt(posSucu.getText()) >= 0)
            {

                obj.agregarmodelo(Integer.parseInt(posSucu.getText()), new Caballero(fecha.getText(), costo.getText(), SoN.getText(), modelo.getText(), Integer.parseInt(anio.getText()), tipocalzado.getText()));

            } else
            {
                Mensaje.error(this, "Esa posición de sucursal no está registrada.");
            }
            this.dispose();
        } else
        {
            Mensaje.error(this, "Por favor, llene todos los campos.");
        }
    }//GEN-LAST:event_terminarMouseClicked

    private void btnTerminarKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnTerminarKeyPressed
    {//GEN-HEADEREND:event_btnTerminarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerminarKeyPressed

    private void cancelar1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cancelar1MouseClicked
    {//GEN-HEADEREND:event_cancelar1MouseClicked
        this.dispose();
    }//GEN-LAST:event_cancelar1MouseClicked

    private void btnCancelar1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnCancelar1KeyPressed
    {//GEN-HEADEREND:event_btnCancelar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar1KeyPressed

    private void cambiar1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cambiar1MouseClicked
    {//GEN-HEADEREND:event_cambiar1MouseClicked
        fecha.setEnabled(false);
        costo.setEnabled(false);
        SoN.setEnabled(false);
        posSucu.setEnabled(true);
        this.btnCambiar.setVisible(false);
        this.cambiar.setVisible(false);
    }//GEN-LAST:event_cambiar1MouseClicked

    private void siguiente1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_siguiente1MouseClicked
    {//GEN-HEADEREND:event_siguiente1MouseClicked
        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()))
        {
            modelo.setEnabled(true);
            anio.setEnabled(true);
            tipocalzado.setEnabled(true);
            jLabel12.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jLabel10.setEnabled(true);
            btnTerminar.setVisible(true);
            terminar.setVisible(true);
            //QUITAR BOTON CAMBIAR
            this.btnCambiar.setVisible(false);
            this.cambiar.setVisible(false);
        } else
        {
            Mensaje.error(this, "Por favor, llene todos los campos.");
        }
    }//GEN-LAST:event_siguiente1MouseClicked

    private void btnSiguiente1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnSiguiente1KeyPressed
    {//GEN-HEADEREND:event_btnSiguiente1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente1KeyPressed

    private void terminar1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_terminar1MouseClicked
    {//GEN-HEADEREND:event_terminar1MouseClicked
        try
        {
            if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()) && !"".equals(modelo.getText()) && !"".equals(anio.getText()) && !"".equals(tipocalzado.getText()))
            {
                if (Integer.parseInt(posSucu.getText()) < obj.getAutoServicios().size() && Integer.parseInt(posSucu.getText()) >= 0)
                {

                    obj.agregarmodelo(Integer.parseInt(posSucu.getText()), new Caballero(fecha.getText(), costo.getText(), SoN.getText(), modelo.getText(), Integer.parseInt(anio.getText()), tipocalzado.getText()));

                } else
                {
                    Mensaje.error(this, "Esa posición de sucursal no está registrada.");
                }
                this.dispose();
            } else
            {
                Mensaje.error(this, "Por favor, llene todos los campos.");
            }

        } catch (Exception e)
        {
            Mensaje.error(this, "Se esperaba un número entero");

        }


    }//GEN-LAST:event_terminar1MouseClicked

    private void btnTerminar1KeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_btnTerminar1KeyPressed
    {//GEN-HEADEREND:event_btnTerminar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTerminar1KeyPressed

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCancelarMouseEntered
    {//GEN-HEADEREND:event_btnCancelarMouseEntered
        btnCancelar.setVisible(false);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void cancelarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cancelarMouseEntered
    {//GEN-HEADEREND:event_cancelarMouseEntered
        btnCancelar.setVisible(false);
    }//GEN-LAST:event_cancelarMouseEntered

    private void btnCancelar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCancelar1MouseExited
    {//GEN-HEADEREND:event_btnCancelar1MouseExited
        btnCancelar.setVisible(true);
    }//GEN-LAST:event_btnCancelar1MouseExited

    private void cancelar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cancelar1MouseExited
    {//GEN-HEADEREND:event_cancelar1MouseExited
        btnCancelar.setVisible(true);
    }//GEN-LAST:event_cancelar1MouseExited

    private void btnCambiarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCambiarMouseEntered
    {//GEN-HEADEREND:event_btnCambiarMouseEntered
        btnCambiar.setVisible(false);
    }//GEN-LAST:event_btnCambiarMouseEntered

    private void cambiarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cambiarMouseEntered
    {//GEN-HEADEREND:event_cambiarMouseEntered
        btnCambiar.setVisible(false);
    }//GEN-LAST:event_cambiarMouseEntered

    private void btnCambiar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCambiar1MouseExited
    {//GEN-HEADEREND:event_btnCambiar1MouseExited
        btnCambiar.setVisible(true);
    }//GEN-LAST:event_btnCambiar1MouseExited

    private void cambiar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_cambiar1MouseExited
    {//GEN-HEADEREND:event_cambiar1MouseExited
        btnCambiar.setVisible(true);
    }//GEN-LAST:event_cambiar1MouseExited

    private void btnSiguienteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguienteMouseEntered
    {//GEN-HEADEREND:event_btnSiguienteMouseEntered
        btnSiguiente.setVisible(false);
    }//GEN-LAST:event_btnSiguienteMouseEntered

    private void siguienteMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_siguienteMouseExited
    {//GEN-HEADEREND:event_siguienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteMouseExited

    private void siguienteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_siguienteMouseEntered
    {//GEN-HEADEREND:event_siguienteMouseEntered
        btnSiguiente.setVisible(false);
    }//GEN-LAST:event_siguienteMouseEntered

    private void btnSiguiente1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguiente1MouseExited
    {//GEN-HEADEREND:event_btnSiguiente1MouseExited
        btnSiguiente.setVisible(true);
    }//GEN-LAST:event_btnSiguiente1MouseExited

    private void siguiente1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_siguiente1MouseExited
    {//GEN-HEADEREND:event_siguiente1MouseExited
        btnSiguiente.setVisible(true);
    }//GEN-LAST:event_siguiente1MouseExited

    private void btnTerminarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnTerminarMouseEntered
    {//GEN-HEADEREND:event_btnTerminarMouseEntered
        btnTerminar.setVisible(false);
    }//GEN-LAST:event_btnTerminarMouseEntered

    private void terminarMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_terminarMouseEntered
    {//GEN-HEADEREND:event_terminarMouseEntered
        btnTerminar.setVisible(false);
    }//GEN-LAST:event_terminarMouseEntered

    private void btnTerminar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnTerminar1MouseExited
    {//GEN-HEADEREND:event_btnTerminar1MouseExited
        btnTerminar.setVisible(true);
    }//GEN-LAST:event_btnTerminar1MouseExited

    private void terminar1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_terminar1MouseExited
    {//GEN-HEADEREND:event_terminar1MouseExited
        btnTerminar.setVisible(true);
    }//GEN-LAST:event_terminar1MouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCancelarMouseClicked
    {//GEN-HEADEREND:event_btnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelar1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCancelar1MouseClicked
    {//GEN-HEADEREND:event_btnCancelar1MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelar1MouseClicked

    private void btnCambiar1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCambiar1MouseClicked
    {//GEN-HEADEREND:event_btnCambiar1MouseClicked
        fecha.setEnabled(false);
        costo.setEnabled(false);
        SoN.setEnabled(false);
        posSucu.setEnabled(true);
        this.btnCambiar.setVisible(false);
        this.cambiar.setVisible(false);
    }//GEN-LAST:event_btnCambiar1MouseClicked

    private void btnSiguiente1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguiente1MouseClicked
    {//GEN-HEADEREND:event_btnSiguiente1MouseClicked
        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()))
        {
            modelo.setEnabled(true);
            anio.setEnabled(true);
            tipocalzado.setEnabled(true);
            jLabel12.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jLabel10.setEnabled(true);
            btnTerminar.setVisible(true);
            terminar.setVisible(true);
            //QUITAR BOTON CAMBIAR
            this.btnCambiar.setVisible(false);
            this.cambiar.setVisible(false);
        } else
        {
            Mensaje.error(this, "Por favor, llene todos los campos.");
        }
    }//GEN-LAST:event_btnSiguiente1MouseClicked

    private void btnTerminar1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnTerminar1MouseClicked
    {//GEN-HEADEREND:event_btnTerminar1MouseClicked
        if (!"".equals(fecha.getText()) && !"".equals(costo.getText()) && !"".equals(SoN.getText()) && !"".equals(posSucu.getText()) && !"".equals(modelo.getText()) && !"".equals(anio.getText()) && !"".equals(tipocalzado.getText()))
        {
//            if (obj2.validaSucursal(Integer.parseInt(posSucu.getText()), obj.getAutoServicios().size()) == true)
            if (Integer.parseInt(posSucu.getText()) < obj.getAutoServicios().size() && Integer.parseInt(posSucu.getText()) >= 0)
            {

                obj.agregarmodelo(Integer.parseInt(posSucu.getText()), new Caballero(fecha.getText(), costo.getText(), SoN.getText(), modelo.getText(), Integer.parseInt(anio.getText()), tipocalzado.getText()));

            } else
            {
                Mensaje.error(this, "Esa posición de sucursal no está registrada.");
            }
            this.dispose();
        } else
        {
            Mensaje.error(this, "Por favor, llene todos los campos.");
        }
    }//GEN-LAST:event_btnTerminar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnACaballero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnACaballero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnACaballero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnACaballero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnACaballero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo1;
    private javax.swing.JTextField SoN;
    private javax.swing.JTextField anio;
    private javax.swing.JPanel btnCambiar;
    private javax.swing.JPanel btnCambiar1;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnCancelar1;
    private javax.swing.JPanel btnSiguiente;
    private javax.swing.JPanel btnSiguiente1;
    private javax.swing.JPanel btnTerminar;
    private javax.swing.JPanel btnTerminar1;
    private javax.swing.JLabel cambiar;
    private javax.swing.JLabel cambiar1;
    private javax.swing.JLabel cancelar;
    private javax.swing.JLabel cancelar1;
    private javax.swing.JTextField costo;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField posSucu;
    private javax.swing.JLabel siguiente;
    private javax.swing.JLabel siguiente1;
    private javax.swing.JLabel terminar;
    private javax.swing.JLabel terminar1;
    private javax.swing.JTextField tipocalzado;
    // End of variables declaration//GEN-END:variables
}
