/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zapateria;

import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author User
 */
public class vtnIniciarSesion extends javax.swing.JFrame
{

    /**
     * Creates new form vtnIniciarSesion
     */
    public vtnIniciarSesion()
    {
        initComponents();
        setIconImage(getIconImage());
    }

    //Icono del jframe
    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnContraseña = new javax.swing.JTextField();
        btnCorreo1 = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JPanel();
        Siguiente = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JPanel();
        Siguiente1 = new javax.swing.JLabel();
        btnRegistrarse1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 307, 10));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("¿No tienes cuenta?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 318, -1, -1));

        btnRegistrarse.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(51, 51, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseEntered(evt);
            }
        });
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 316, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Iniciar sesión");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 45, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Correo electrónico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 92, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 151, -1, -1));

        btnContraseña.setBackground(new java.awt.Color(231, 230, 230));
        btnContraseña.setForeground(new java.awt.Color(153, 153, 153));
        btnContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContraseñaMouseClicked(evt);
            }
        });
        btnContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(btnContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 170, 227, 31));

        btnCorreo1.setBackground(new java.awt.Color(231, 230, 230));
        btnCorreo1.setForeground(new java.awt.Color(153, 153, 153));
        btnCorreo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCorreo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCorreo1MouseClicked(evt);
            }
        });
        btnCorreo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 113, 227, -1));

        btnSiguiente.setBackground(new java.awt.Color(34, 22, 217));
        btnSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseExited(evt);
            }
        });

        Siguiente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(255, 255, 255));
        Siguiente.setText("Siguiente");
        Siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SiguienteMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnSiguienteLayout = new javax.swing.GroupLayout(btnSiguiente);
        btnSiguiente.setLayout(btnSiguienteLayout);
        btnSiguienteLayout.setHorizontalGroup(
            btnSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSiguienteLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(Siguiente)
                .addGap(85, 85, 85))
        );
        btnSiguienteLayout.setVerticalGroup(
            btnSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Siguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 238, -1, -1));

        btnSiguiente1.setBackground(new java.awt.Color(97, 5, 16));
        btnSiguiente1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnSiguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseExited(evt);
            }
        });

        Siguiente1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Siguiente1.setForeground(new java.awt.Color(255, 255, 255));
        Siguiente1.setText("Siguiente");
        Siguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Siguiente1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Siguiente1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSiguiente1Layout = new javax.swing.GroupLayout(btnSiguiente1);
        btnSiguiente1.setLayout(btnSiguiente1Layout);
        btnSiguiente1Layout.setHorizontalGroup(
            btnSiguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSiguiente1Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(Siguiente1)
                .addGap(85, 85, 85))
        );
        btnSiguiente1Layout.setVerticalGroup(
            btnSiguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Siguiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 238, -1, -1));

        btnRegistrarse1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRegistrarse1.setForeground(new java.awt.Color(97, 5, 16));
        btnRegistrarse1.setText("Registrarse");
        btnRegistrarse1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarse1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarse1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarse1MouseExited(evt);
            }
        });
        jPanel1.add(btnRegistrarse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 316, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 355));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContraseñaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContraseñaActionPerformed
    {//GEN-HEADEREND:event_btnContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContraseñaActionPerformed

    private void btnCorreo1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCorreo1ActionPerformed
    {//GEN-HEADEREND:event_btnCorreo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCorreo1ActionPerformed

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarseMouseClicked
    {//GEN-HEADEREND:event_btnRegistrarseMouseClicked
        new vtnRegistrarse().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void SiguienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SiguienteMouseClicked
    {//GEN-HEADEREND:event_SiguienteMouseClicked
        new vtnPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SiguienteMouseClicked

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguienteMouseClicked
    {//GEN-HEADEREND:event_btnSiguienteMouseClicked
        new vtnPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void btnCorreo1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCorreo1MouseClicked
    {//GEN-HEADEREND:event_btnCorreo1MouseClicked
        btnCorreo1.setText("");
    }//GEN-LAST:event_btnCorreo1MouseClicked

    private void btnContraseñaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnContraseñaMouseClicked
    {//GEN-HEADEREND:event_btnContraseñaMouseClicked
        btnContraseña.setText("");
    }//GEN-LAST:event_btnContraseñaMouseClicked

    private void btnSiguienteMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguienteMouseExited
    {//GEN-HEADEREND:event_btnSiguienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteMouseExited

    private void btnSiguienteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguienteMouseEntered
    {//GEN-HEADEREND:event_btnSiguienteMouseEntered
        btnSiguiente.setVisible(false);
    }//GEN-LAST:event_btnSiguienteMouseEntered

    private void Siguiente1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Siguiente1MouseClicked
    {//GEN-HEADEREND:event_Siguiente1MouseClicked
        new vtnPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Siguiente1MouseClicked

    private void btnSiguiente1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguiente1MouseClicked
    {//GEN-HEADEREND:event_btnSiguiente1MouseClicked
        new vtnPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguiente1MouseClicked

    private void btnSiguiente1MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguiente1MouseEntered
    {//GEN-HEADEREND:event_btnSiguiente1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguiente1MouseEntered

    private void btnSiguiente1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguiente1MouseExited
    {//GEN-HEADEREND:event_btnSiguiente1MouseExited
        btnSiguiente.setVisible(true);
    }//GEN-LAST:event_btnSiguiente1MouseExited

    private void SiguienteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SiguienteMouseEntered
    {//GEN-HEADEREND:event_SiguienteMouseEntered
        btnSiguiente.setVisible(false);
    }//GEN-LAST:event_SiguienteMouseEntered

    private void Siguiente1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Siguiente1MouseExited
    {//GEN-HEADEREND:event_Siguiente1MouseExited
        btnSiguiente.setVisible(true);
    }//GEN-LAST:event_Siguiente1MouseExited

    private void btnRegistrarse1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarse1MouseClicked
    {//GEN-HEADEREND:event_btnRegistrarse1MouseClicked
        new vtnRegistrarse().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarse1MouseClicked

    private void btnRegistrarseMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarseMouseEntered
    {//GEN-HEADEREND:event_btnRegistrarseMouseEntered
        btnRegistrarse.setVisible(false);
    }//GEN-LAST:event_btnRegistrarseMouseEntered

    private void btnRegistrarse1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnRegistrarse1MouseExited
    {//GEN-HEADEREND:event_btnRegistrarse1MouseExited
        btnRegistrarse.setVisible(true);
    }//GEN-LAST:event_btnRegistrarse1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnIniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnIniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Siguiente;
    private javax.swing.JLabel Siguiente1;
    private javax.swing.JTextField btnContraseña;
    private javax.swing.JTextField btnCorreo1;
    private javax.swing.JLabel btnRegistrarse;
    private javax.swing.JLabel btnRegistrarse1;
    private javax.swing.JPanel btnSiguiente;
    private javax.swing.JPanel btnSiguiente1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
