/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zapateria;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class vtnRegistrarse extends javax.swing.JFrame
{

    /**
     * Creates new form vtnRegistrarse
     */
    public vtnRegistrarse()
    {
        initComponents();
        setIconImage(getIconImage());
    }

    //Icono del jframe
    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAnio = new javax.swing.JComboBox<>();
        btnMes = new javax.swing.JComboBox<>();
        btnDia = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCorreo = new javax.swing.JTextField();
        btnContraseña = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JPanel();
        Siguiente = new javax.swing.JLabel();
        btnSiguiente1 = new javax.swing.JPanel();
        Siguiente1 = new javax.swing.JLabel();
        btnIniciarSesion1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnContraseña1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 305, 10));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("¿Ya tienes una cuenta?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 373, -1, -1));

        btnIniciarSesion.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(145, 58, 68));
        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 371, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Registrarse");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 35, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("¿Cuál es su fecha de nacimiento?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 82, -1, -1));

        btnAnio.setBackground(new java.awt.Color(231, 230, 230));
        btnAnio.setForeground(new java.awt.Color(102, 102, 102));
        btnAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", " " }));
        btnAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 108, 71, -1));

        btnMes.setBackground(new java.awt.Color(231, 230, 230));
        btnMes.setForeground(new java.awt.Color(102, 102, 102));
        btnMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre ", "Noviembre", "Diciembre" }));
        btnMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesActionPerformed(evt);
            }
        });
        jPanel1.add(btnMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 108, 71, -1));

        btnDia.setBackground(new java.awt.Color(231, 230, 230));
        btnDia.setForeground(new java.awt.Color(102, 102, 102));
        btnDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(btnDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 108, 71, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Correo electrónico:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Confirmar  Contraseña:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btnCorreo.setBackground(new java.awt.Color(231, 230, 230));
        btnCorreo.setForeground(new java.awt.Color(153, 153, 153));
        btnCorreo.setText("Introduce tu correo electrónico...");
        btnCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCorreoMouseClicked(evt);
            }
        });
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 249, 31));

        btnContraseña.setBackground(new java.awt.Color(231, 230, 230));
        btnContraseña.setForeground(new java.awt.Color(153, 153, 153));
        btnContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContraseñaMouseClicked(evt);
            }
        });
        btnContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(btnContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 249, 31));

        btnSiguiente.setBackground(new java.awt.Color(51, 51, 255));
        btnSiguiente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiguienteMouseEntered(evt);
            }
        });

        Siguiente.setBackground(new java.awt.Color(102, 102, 255));
        Siguiente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(255, 255, 255));
        Siguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Siguiente.setText("Siguiente");
        Siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SiguienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SiguienteMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnSiguienteLayout = new javax.swing.GroupLayout(btnSiguiente);
        btnSiguiente.setLayout(btnSiguienteLayout);
        btnSiguienteLayout.setHorizontalGroup(
            btnSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Siguiente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        btnSiguienteLayout.setVerticalGroup(
            btnSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 249, -1));

        btnSiguiente1.setBackground(new java.awt.Color(51, 51, 255));
        btnSiguiente1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        btnSiguiente1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSiguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiguiente1MouseExited(evt);
            }
        });

        Siguiente1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Siguiente1.setForeground(new java.awt.Color(255, 255, 255));
        Siguiente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Siguiente1.setText("Siguiente");
        Siguiente1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Siguiente1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Siguiente1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSiguiente1Layout = new javax.swing.GroupLayout(btnSiguiente1);
        btnSiguiente1.setLayout(btnSiguiente1Layout);
        btnSiguiente1Layout.setHorizontalGroup(
            btnSiguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Siguiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        btnSiguiente1Layout.setVerticalGroup(
            btnSiguiente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Siguiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jPanel1.add(btnSiguiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 249, -1));

        btnIniciarSesion1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnIniciarSesion1.setForeground(new java.awt.Color(97, 5, 16));
        btnIniciarSesion1.setText("Iniciar sesión");
        btnIniciarSesion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIniciarSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesion1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesion1MouseExited(evt);
            }
        });
        jPanel1.add(btnIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 371, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Contraseña:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        btnContraseña1.setBackground(new java.awt.Color(231, 230, 230));
        btnContraseña1.setForeground(new java.awt.Color(153, 153, 153));
        btnContraseña1.setText("Introduce tu contraseña...");
        btnContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContraseña1MouseClicked(evt);
            }
        });
        btnContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContraseña1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 249, 31));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Contraseña:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnIniciarSesionMouseClicked
    {//GEN-HEADEREND:event_btnIniciarSesionMouseClicked
        new vtnIniciarSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarSesionMouseClicked

    private void btnMesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMesActionPerformed
    {//GEN-HEADEREND:event_btnMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMesActionPerformed

    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCorreoActionPerformed
    {//GEN-HEADEREND:event_btnCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCorreoActionPerformed

    private void btnContraseñaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnContraseñaActionPerformed
    {//GEN-HEADEREND:event_btnContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContraseñaActionPerformed

    private void btnSiguienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguienteMouseClicked
    {//GEN-HEADEREND:event_btnSiguienteMouseClicked
        new vtnInicio().setVisible(true);
    }//GEN-LAST:event_btnSiguienteMouseClicked

    private void SiguienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SiguienteMouseClicked
    {//GEN-HEADEREND:event_SiguienteMouseClicked
        new vtnInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SiguienteMouseClicked

    private void btnCorreoMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnCorreoMouseClicked
    {//GEN-HEADEREND:event_btnCorreoMouseClicked
        btnCorreo.setText("");
    }//GEN-LAST:event_btnCorreoMouseClicked

    private void btnContraseñaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnContraseñaMouseClicked
    {//GEN-HEADEREND:event_btnContraseñaMouseClicked
        btnContraseña.setText("");
    }//GEN-LAST:event_btnContraseñaMouseClicked

    private void Siguiente1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Siguiente1MouseClicked
    {//GEN-HEADEREND:event_Siguiente1MouseClicked
        new vtnInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Siguiente1MouseClicked

    private void btnSiguiente1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguiente1MouseClicked
    {//GEN-HEADEREND:event_btnSiguiente1MouseClicked
        new vtnInicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguiente1MouseClicked

    private void btnSiguienteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguienteMouseEntered
    {//GEN-HEADEREND:event_btnSiguienteMouseEntered
        btnSiguiente.setVisible(false);
    }//GEN-LAST:event_btnSiguienteMouseEntered

    private void SiguienteMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_SiguienteMouseEntered
    {//GEN-HEADEREND:event_SiguienteMouseEntered
        btnSiguiente.setVisible(false);
    }//GEN-LAST:event_SiguienteMouseEntered

    private void btnSiguiente1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnSiguiente1MouseExited
    {//GEN-HEADEREND:event_btnSiguiente1MouseExited
        btnSiguiente.setVisible(true);
    }//GEN-LAST:event_btnSiguiente1MouseExited

    private void Siguiente1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_Siguiente1MouseExited
    {//GEN-HEADEREND:event_Siguiente1MouseExited
        btnSiguiente.setVisible(true);
    }//GEN-LAST:event_Siguiente1MouseExited

    private void btnIniciarSesion1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnIniciarSesion1MouseClicked
    {//GEN-HEADEREND:event_btnIniciarSesion1MouseClicked
        new vtnIniciarSesion().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIniciarSesion1MouseClicked

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnIniciarSesionMouseEntered
    {//GEN-HEADEREND:event_btnIniciarSesionMouseEntered
        btnIniciarSesion.setVisible(false);
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesion1MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnIniciarSesion1MouseExited
    {//GEN-HEADEREND:event_btnIniciarSesion1MouseExited
        btnIniciarSesion.setVisible(true);
    }//GEN-LAST:event_btnIniciarSesion1MouseExited

    private void btnContraseña1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContraseña1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContraseña1MouseClicked

    private void btnContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContraseña1ActionPerformed

    private void btnAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(vtnRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(vtnRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(vtnRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(vtnRegistrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new vtnRegistrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Siguiente;
    private javax.swing.JLabel Siguiente1;
    private javax.swing.JComboBox<String> btnAnio;
    private javax.swing.JTextField btnContraseña;
    private javax.swing.JTextField btnContraseña1;
    private javax.swing.JTextField btnCorreo;
    private javax.swing.JComboBox<String> btnDia;
    private javax.swing.JLabel btnIniciarSesion;
    private javax.swing.JLabel btnIniciarSesion1;
    private javax.swing.JComboBox<String> btnMes;
    private javax.swing.JPanel btnSiguiente;
    private javax.swing.JPanel btnSiguiente1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
